---
driver:
  name: proxy
  host: localhost
  reset_command: "exit 0"
  port: 5985
  username: <%= ENV["machine_user"] %>
  password: <%= ENV["machine_pass"] %>

provisioner:
  name: chef_zero
  retry_on_exit_code:
    - 35 # 35 is the exit code signaling that the node is rebooting
  max_retries: 2
  wait_for_retry: 90

platforms:
  - name: windows-2012R2

suites:
  - name: client
    run_list:
      - recipe[sql_server::default]
    attributes: { sql_server: { accept_eula: true } }
  - name: install
    run_list:
      - recipe[test::install]
    verifier:
      inspec_tests:
        - test/integration/install
    attributes: { sql_server: { accept_eula: true, version: 2012, server_sa_password: Supersecurepassword123 } }
