suites:
  - name: default
    includes:
      - ws2k12r2
      - ws2k8r2
    run_list: 
      - recipe[sql_server::default]
  - name: client
    run_list:
      - recipe[sql_server::default]
    attributes: { sql_server: { accept_eula: true } }
  - name: server2008r2
    run_list:
      - recipe[sql_server::server]
    attributes: { sql_server: { accept_eula: true, version: 2008R2, server_sa_password: Supersecurepassword123 } }
  - name: server2012
    run_list:
      - recipe[sql_server::server]
    attributes: { sql_server: { accept_eula: true, version: 2012, server_sa_password: Supersecurepassword123 } }
  - name: server2014
    run_list:
      - recipe[sql_server::server]
    attributes: { sql_server: { accept_eula: true, version: 2014, server_sa_password: Supersecurepassword123 } }
  - name: server2016
    run_list:
      - recipe[sql_server::server]
    attributes: { sql_server: { accept_eula: true, version: 2016, server_sa_password: Supersecurepassword123 } }
